# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]

jobs:
  job1:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v2
      with:
        java-version: '14'
        distribution: 'adopt'
    - name: Cache maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Create release folder
      run: mkdir release
    - name: Build executable - linux
      if: ${{ runner.os == 'Linux' }}
      run: |
        sh build-linux.sh
        tar -czvf AutoTyper.tar.gz AutoTyper
        mv AutoTyper.* *.deb release
    - name: Build executable - others
      if: ${{ runner.os != 'Linux' }}
      run: |
        sh build.sh
        mv AutoTyper-*.* release
    - run: mv target/AutoTyper-*-shaded.jar release
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: release
        path: release/
      
  job2:
    name: Release
    needs: job1
    runs-on: ubuntu-latest
    steps:
    - name: Get release artifacts
      uses: actions/download-artifact@v2
      with:
        name: release
    - name: Create release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: '*'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
