# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]

jobs:
  job1:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 14
      uses: actions/setup-java@v2
      with:
        java-version: '14'
        distribution: 'adopt'
    - name: set env
      run: |
        echo ::set-env name=PROJECT::$(echo 'AutoTyper')
        echo ::set-env name=MAIN_CLASS::$(echo 'com.sidetrackd.autotyper.App'
        echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF#refs/*/})
    - name: cache maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: build with maven
      run: mvn package
    - run: mkdir release
    - name: build executable for linux
      if: ${{ runner.os == 'Linux' }}
      run: |
        jpackage --input target/ --name $PROJECT --main-jar $PROJECT-$RELEASE_VERSION-shaded.jar --main-class $MAIN_CLASS --type app-image
        jpackage --name $PROJECT-$RELEASE_VERSION --app-image $PROJECT
        tar -czvf $PROJECT-$RELEASE_VERSION.tar.gz $PROJECT/
        mv $PROJECT-$RELEASE_VERSION.* release
    - name: build executable for others
      if: ${{ runner.os != 'Linux' }}
      run: |
        jpackage --input target/ --name $PROJECT-$RELEASE_VERSION --main-jar $PROJECT-$RELEASE_VERSION-shaded.jar --main-class $MAIN_CLASS
        mv $PROJECT-$RELEASE_VERSION.* release
    - run: mv target/$PROJECT-$RELEASE_VERSION-shaded.jar release
    - name: upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: release
        path: release/
      
  job2:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: set env
      run: |
        echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF#refs/*/})
        echo ::set-env name=PRERELEASE::$(`if [[ $RELEASE_VERSION =~ "-alpha" ]] || [[ $RELEASE_VERSION =~ "-beta" ]]; then echo true; else echo false; fi`)
    - name: get release artifacts
      uses: actions/download-artifact@v2
      with:
        name: release
    - name: unzip contents
      run: unzip release.zip
    - name: create release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        prerelease: ${{ PRERELEASE == 1 }}
        files: release/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
